# version: "3.8"

# services:
#   fastapi:
#     container_name: fastapi_app
#     build: .
#     ports:
#       - "8000:8000"
#     restart: always
#     env_file:
#       - .env # Load environment variables

version: "3.8"

services:
  fastapi:
    container_name: fastapi_app
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    # Removed depends_on: - redis
