# version: "3.8"

# services:
#   fastapi:
#     container_name: fastapi_app
#     build: .
#     ports:
#       - "8000:8000"
#     restart: always
#     env_file:
#       - .env # Load environment variables

version: "3.8"

services:
  fastapi:
    container_name: fastapi_app
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:6-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
